name: Feature request
description: Request a new feature
labels: ['type: feature']
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature. If you intend to submit a PR for this feature, tell us how in the description. Thanks!
      placeholder: Feature description
    validations:
      required: true
